### ISSUE TITLE
len is a required element of PointDefinition without a default

### ISSUE THREAD

**Issue by wz2b** [sunspec/models#143]
The 'len' field on a point definition is specified as:
```xml
  <xs:complexType name="PointDefinition">
    ...
    <xs:attribute name="len" type="xs:integer" />
    ...
  </xs:complexType>
```

The rules of XSD are as follows:

[The default value for both the minOccurs and the maxOccurs attributes is 1. Thus, when an element such as comment is declared without a maxOccurs attribute, the element may not occur more than once. ](https://www.w3.org/TR/xmlschema-0/#:~:text=The%20default%20value%20for%20both,not%20occur%20more%20than%20once.)

There are a lot of points throughout the XML documents that don't specify a len, but the defaults for minOccurs and maxOccurs says that it should be mandatory.  For what I'm doing, it's important to me that the len be specified.

For the majority of these cases, the field type is 16 bits long.  Several other types appear with no length.  Trying to sort this out, I refer to the "SunSpec Information Model Specification" version 1.9.  Point types of concern:

 * pad, What's confusing about this is that the specification says there is a type "pad16" but no such type exists in the schema.  The actual number of padding bytes depends on the number of bytes above if you're trying to round to either 32-bit or 64-bit alignment.  This means you might need to add 16, 24, 32, 40, 04 48 bits.  Rather than figure this out, and especially in light of the fact that 'len' is required (per the schema), I think the len has to be explicit in all these point definitions
 * sunssf - a scaling factor that appears as a point type in the schema and is explained in the specification to be a 16-bit value
 * count - points don't specify a length, but they appear to be 16 bit - are the always?

I think the right thing to do here is to be explicit about the lengths in all cases.  That would match the intent of the schema, and eliminate the need for logic on the consuming end.

This is similar to some of the concerns discussed in #36 which closed.

If someone can give me some official guidance I'll submit a PR to add in the missing lengths.

In the short term, in Kotlin, I'm making some assumptions based on the type:

```kotlin
    fun inferLength(type: String): Int {
        return when (type) {
            "int16" -> 1
            "uint16" -> 1
            "count" -> 1
            "acc16" -> 1
            "string" -> 0
            "int32" -> 2
            "uint32" -> 2
            "float32" -> 2
            "acc32" -> 2
            "int64" -> 4
            "uint64" -> 4
            "float64" -> 4
            "bitfield16" -> 1
            "bitfield32" -> 2
            "sunssf" -> 1
            "pad" -> 1
            "ipaddr" -> 2
            "ipv6addr" -> 8
            "eui48" -> 3
            else -> 0
        }
    }
```

I think all of that is right except for 'pad' which has a variable length.

**Comment by bobfox** [comment]
As I mentioned in issue 62, we are deprecating support for xml and focusing on getting the best json implementation we can, I know this is a disappointing answer for you but I hope it is not too difficult if you choose to transition to json.
The issue regarding the specification of length has also been discussed in the json encoding and the decision was only include the len (now called size) attribute for strings. The name was changed to 'size' to try to emphasize that the value is the number of Modbus registers rather than the number of bytes. The size of the elements other than string are fixed and specifying them in the point definition is a potential source of error. In general, attributes that have default values are also not specified in the definition file. The objective is to generate the json files programmatically to provide a uniform approach. 
Once again, I am sorry this is not the direction you prefer. I hope it is workable for you and that you continue to provide input.

**Comment by wz2b** [comment]
I have switched my kotlin model generator over to use the json, so I think this can be simply closed.
