### ISSUE TITLE
PMin not in models

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#200]
1547-2018 specifies **_PMin_** as the minimum active power output of the DER. It's used in _active power-reactive power_, _voltage-active power_, and _freq-droop_. I cannot find it in the DER models.

According to Greg Kern, our power architect, there are multiple use cases where setting Pmin to -1.0 or 0.0 or some other number are needed. The requested range is -1.00 pu to 1.00 pu.

From Greg:

> Most PV inverters will likely hardcode the number internally.  For stacking I might want to be able to set Pmin to -1.0, our default will be 0.0.  People who build microgrids would want to be able to program Pmin to -1.0 to help stabilize micro grid frequency.  How they do that is through the communication interface.

**Comment by bobfox** [comment]
PMin is not specified as an adjustable setting in 1547-2018 and I am not sure it addresses PMin < 0 in the 1547 spec. Is there a specification that describes what is means for PMin < 0? When PMin < 0, is that addressing the charging capabilities and does PMin = -1.0 reflect the maximum charge rating? I am not opposed to supporting it, but would like to be able to understand and describe what it means.

**Comment by GregKern** [comment]
SunSpec must support not only the minimum requirements of 1547-2018 but also the ability for equipment to use SunSpec to pass certification testing specified in 1547.1-2020.

section 5.15.2.2 step r) of 1547.1-2020 reads as follows

"For EUTs that can absorb power, rerun Characteristic 1 allowing the unit to absorb power by
programming a negative Pmin."

If SunSpec refuses to support programming a negative Pmin, then SunSpec is not a viable communication means for ESS.

**Comment by wz2b** [comment]
Could their intent be that you don't set a negative Pmin but that you perform things like you are describing by advancing or retarding the phase?

**Comment by GregKern** [comment]
No, this is for Freq-Droop, in the case when grid frequency goes high, DERs with the ability to absorb power can and in some cases will be configured to pull power in from the grid to the DER to help pull grid frequency back down.  More typically, an inverter with a battery (a type of ESS) connected to a micro grid where the micro grid controllers want to help stabilize the microgrid by configuring the ESS for full charge or discharge on FreqDroop.  but in order to make this happen we have to be able to communicate the Pmin parameter.

**Comment by jayatsandia** [comment]
Would 702:WDisChaRteMaxRtg work to change Pmin from 0 to -1 pu?

I would think this would provide the necessary behavior to evaluate the 1547.1-2020 Freq-Droop for battery-based DER, as this sets a negative Pmin since this point is defined as the "Maximum active power discharge rate in watts."

**Comment by GregKern** [comment]
702:WChaRteMax is an independent setting that would need to be set to allow the unit to charge while freq-drooping, but there still needs to be an independant Pmin setting within the freq-droop function.  Not all utilities require absorption of power during freq-droop.  Some would argue that encroaches on Load Dispatch.  CA Rule 21 curves on freq droop go down to zero then stop, and do not go negative, implying a Pmin default setting of 0 for ESS.  What harm is there in providing an optional Pmin setting under freq-droop for those of us who have ESS and need to be able to execute the 1547.1-2020 test procedure?

1547-2018 eratta defines Pmin as follows
_pmin   is the minimum active power output due to DER prime mover constraints, in p.u. of the DER active power
rating in kW_

and 1547.1-2020 CLEARLY indicates Pmin is a programmed parameter.
_r) For EUTs that can absorb power, rerun Characteristic 1 allowing the unit to absorb power by
**programming a negative Pmin**._

**Comment by GregKern** [comment]
ps. setting Pmin to zero for freq-droop is also needed in CA to be able to comply with Tariffs that only allow batteries to be charged from solar and NOT the grid in order to qualify for net metering.

**Comment by jayatsandia** [comment]
I see your point Greg. This would create a Freq-Droop cut off line at the bottom of the curve, and it's defined as a parameter in IEEE 1547-2018. I agree that it should be adjustable based on the IEEE 1547.1 test procedure. Play around with the curve in the attached sheet if you like. 

[Freq-droop.xlsx](https://github.com/sunspec/models/files/5928518/Freq-droop.xlsx)

**Comment by bobfox** [comment]
At this point, we are just trying to specify what PMin is and how to use it. Ideally that would all be in 1547 but it seems incomplete for a full understanding. The errata definition seems to be oriented to generation. It indicates that PMin is expressed as output and in terms of the DER active power rating. It seems like many systems may have a different limit for absorbing active power and generation. For example, if the generation rating is 10KW and the charge rating is 5KW, what value does -1.0 represent, -5KW or -10KW? And does this matter?

**Comment by GregKern** [comment]
yes, Pmin is positive for active power output (or generation or injection) and negative for active power consumption (charging or absorption).

Yes, some systems will have limits on how much active power absorption (charging) they can do, but this doesn't change the basis.  

Use the same basis for generation and charging.   In your example, -1.0 Pmin would represent -10kW, however the unit would never operate at that point and would be limited by other limits to -5kW.  and if the battery is full, charging would be limited even further.

imagine how confusing programming would be if we decided that positive numbers basis should be  two's complement but negative numbers basis should be ten's complement.  it is an apt analogy.

Pmin is clearly a per unit parameter since the freq-droop equation is in per unit.

I would argue that in the absence of clear guidance, only one basis should be used, positive active power rating.  The standard does not state or even imply that we should use two separate basses.

I would strongly argue against trying to define a positive and negative basis (dont overcomplicate this) for such a per unit parameter, because that would effectively change the slope of the response, an unintended consequence, and possible impact on system stability.  The basis for Pmin should be exactly what is written in 1547-2018, the 'p. u. of the active power rating'.

Here is another place where 1547-2018 DOES NOT define a separate positive and negative basis, Reactive Power.  Table 7 of 1547-2018 defines the minimum reactive power injection and absorption capabilities of Cat A and B DERs, in that case the basis is Apparent Power Rating, Cat A injection capability is 0.44 pu (44%) and for absorption 0.25 pu (25%).  We DID NOT try to define a different basis for positive and negative reactive powers.  If anything, in the future, to eliminate this question, 1547-2018 should set the basis for all power ratings (apparent, active and reactive) as rated Apparent Power.  now of course there is no such thing as a negative apparent power rating.

**Comment by GregKern** [comment]
FYI
be aware that Pmin does not have the same meaning throughout IEEE 1547.1-2020.  It's meaning may vary from test to test.
for example, in section 5.14.2 states
    _Pmin – minimum active power (W)
    P’min – for EUTs that can sink power, minimum active power while sinking power (W)_

**Comment by GregKern** [comment]
and in some of those cases Pmin does not represent a communicated parameter but rather a power level as part of a test procedure.

**Comment by bobfox** [comment]
The following changes were proposed to multiple manufacturers and stakeholders today in the weekly FIGII meeting and there were no objections:

PMin be added to SunSpec Modbus model 711 (Freq-Droop) for each set of settings.
PMin is a signed 16-bit value representing a percentage from -100 to 100. The label is Minimum Active Power. The description is: The minimum active power output due to DER prime mover constraints, in percent of the DER active power rating. The valid range is -100 to 100. Support of PMin is optional and not required for 1547-2018 conformance.

We will review at the next Modbus workgroup meeting and proceed if there are no issues.
