### ISSUE TITLE
Model 702 | PFOvrExt/PFUndExt seem to be duplicates of WOvrExtPF/WUndExtPF

### ISSUE THREAD

**Issue by FW22** [sunspec/models#222]
It seems to me that in model 702 the registers PFOvrExt and PFUndExt are duplicating WOvrExtPF and WUndExtPF.
Am I right or am I missing something?

**Comment by bobfox** [comment]
The WOvrExtPF and WUndExtPF values relate to the WOvrExtRtg and WUndExtRtg points. IEEE 1547-2018 has three active power ratings: rating at unity pf, rating at the over-excited pf, rating at the under-excited pf. 1547 requires that reactive power be available at the active power rating. The amount of reactive power that must be available is different for category A and category B devices. Category A device have a different reactive power requirement for over-excited and under-excited regions. Because of these differences the power factor associated with the active power rating was placed in the nameplate information. For inverters, the values in WOvrExtPF and WUndExtPF should be the power factors that correspond to the required max reactive power at full power.

The PFOvrExt/PFUndExt points are additional SunSpec ratings that contain the power factor ratings for the device. These ratings could be much broader than the WOvrExtPF/WUndExtPF point values if the device supports a larger power factor range than the minimum required.

Let me know if this makes sense.
