### ISSUE TITLE
712 Watt-VAr: Open loop response time is missing?

### ISSUE THREAD

**Issue by FW22** [sunspec/models#227]
The interoperability requirements for the Watt-VAr-curve in IEEE1547 point to two different locations.
![image](https://user-images.githubusercontent.com/56593428/128687578-1464bfc1-7dce-408b-b4bf-97d751e6f9c3.png)

First, it points to all parameters in chapter 5.3.4:
![image](https://user-images.githubusercontent.com/56593428/128686371-5154adec-daa0-4514-9fd3-d89f92ff363e.png)

Second, it points to a table that contains the curve points of chapter 5.3.4, adds the enable-switch and excludes the open loop response time:
![image](https://user-images.githubusercontent.com/56593428/128687671-4e3679b1-8d1f-4564-8196-e258dd220afc.png)

Open loop response time is included in model 705 (Volt-VAr), 706 (Volt-Watt) and 711 (Frequency-Droop), but not in 712 (Watt-VAr).

Is this a mistake or a conscious decision?

**Comment by RorkXander** [comment]
I'm running in this issue too.

I looked inside the profile worksheet of IEEE 1547.1-2020 and the Open Loop Response Time exists there.
https://standards.ieee.org/standard/1547_1-2020.html

**Comment by bobfox** [comment]
Table 32 points to Table 9 rather than Table 10. Table 9 contains the points for watt-var which do not include an open loop response time. Table 10 is the volt-watt function which does contain an open loop response time.

The open loop response time contained in the IEEE profile worksheet for watt-var (QP_ORLT_xxx) is a mistake in the worksheet and is not supported by the contents in 1547-2018.
