### ISSUE TITLE
Model 803 ModTmpAvg type

### ISSUE THREAD

**Issue by nefethael** [sunspec/models#34]
Do you know any reason why ModTmpAvg is uint16 instead of int16 like Model 804?

**Comment by silvia2019** [comment]
It appears that it should have been an int16 and we'll investigate the possibility of fixing that.  The main issue is that this model is currently being used by manufacturers. That makes changes difficult to implement without impacting existing implementations.

**Comment by cdbennett** [comment]
We discovered the same issue.  The ModTmpAvg register in Model 803 has three problems, obvious when it's compared to all other temperature value registers:

1. It is unsigned and should be signed
2. It is missing the scale factor (ModTmp_SF)
3. It is missing Units (should be C, although to be really correct all temperatures should use ºC, need the degree symbol, since C is the SI unit coulombs, electric unit of charge)

As long as the scale factor is 0, the only possible problem with correcting this would be that the not-implemented value might be mismatched (0x8000 instead of 0xFFFF).

**Comment by nielsbasjes** [comment]
@silvia2019 I'm curious to get my hands on some real data from one of the devices that support this model. I'm willing to bet they implemented as we expect it here.

**Comment by silvia2019** [comment]
That is a good question.  @bobfox do we have data that can be provided as an example.

**Comment by nielsbasjes** [comment]
If you have access to a real device then this software I wrote may be of use to download the raw data from the device into a form that is easier to use for testing.

I have used this to extract testing data from my own SMA device.

https://github.com/nielsbasjes/energy/blob/master/modbus-parsers/src/test/java/nl/basjes/energy/sunspec/DownloadProcessImageFromRealDevice.java
