### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by cfstras** [sunspec/models#39]
Hello @AndrewMiller1E and @bobfox,

There are a flurry of open pull requests fixing typos, invalid XMLs, and other things.
There are even repos from other users fixing all the issues so the models can be used in production, such as https://github.com/altendky/models/tree/master_plus_pull_requests.

I am guessing there are many willing contributors wanting to fix the issues in this repo, but leaving pull requests open for 3+ years does not inspire helping "upstream".

Sincerely,
cfstras

**Comment by AgronEOS** [comment]
It might be worth creating another "unofficial" fork and get all pull requests into it. I can help too because I am implementing C++ interfaces for various inverters on daily basis.

**Comment by altendky** [comment]
I'm still hopeful (maybe wishing?) that these official repos will spring back to life.  My approach with that branch (and likewise for https://github.com/altendky/pysunspec/tree/master_plus_pull_requests) was to submit stand-alone PRs here and then collect them into the branch.  This maximizes the opportunity for this repo to do sensible reviews on individual PRs and get back into the game.  I figured as long as the PRs weren't stacking on each other that this would work out ok.

Of course, at some point this can't sensibly continue and we'll just have to fully fork.  :[  It would be one thing to do this on the communication libraries where it makes sense for anyone to write an implementation but the models are more of an official definition so I cringe even more considering forking here.  But, when they are as buggy as they are and don't come close to passing their own validation checks...  I dunno...

@cfstras and @AgronEOS, are we comfortable sticking with the PRs here and I'll merge them into my branch?  Or are you two further down the full fork path than I am?

One thing that is lacking and problematic to the workflow of submitting PRs here is that while https://travis-ci.org/sunspec/models exists, it is "not an active repository".  @bobfox, if SunSpec intends to keep this repo going could we at least get master and PRs building and testing as in #37?

**Comment by cfstras** [comment]
@altendky I haven't started my own fork (yet 😬), so I'm ok with having an inofficial fork such as yours. However, I am guessing that many hardware vendors (and companies in the SunSpec Alliance) would not want to use an "un-blessed" repository, thus missing out on these fixes and making it harder for everybody downstream. So I'd obviously prefer this repository not to die...

**Comment by AgronEOS** [comment]
@altendky, on the contrary, the SunSpec models are a great idea but it leaves vendors with incomplete models and almost every one of them had to come up with additional non-sunspec-compliant models.
Therefore, I suggest since your fork contains the fixes, we use your repo, but we take vendors models too, and be more vendor friendly by correcting and publishing their models too. But, please add me as developer to your repo.

**Comment by bobfox** [comment]
All,
As with the pysunspec repo, the issue has been resources and the need to progress with parallel development. SunSpec is acquiring additional resources to apply in the area and is producing an updated information modeling specification that will propose some extensions and a change in encoding strategy. It was intended to address this all together for efficiency but it was delayed longer than was desirable. The updated modeling draft will be released this month. The contents were produced by a  working group of interested contributors. The work group will be restarting once the draft is out and we would welcome participation or comments from all. This and the pysunspec repo are supported and will move forward shortly.
Bob Fox, SunSpec Alliance

**Comment by altendky** [comment]
I think it makes sense to continue the way I have been.  If others want changes in my `master_plus_pull_requests` branches (models or pysunspec) go ahead and PR here and mention me.  I will do reviews and try to judge what I think should and would/will be accepted to the official repos.  This means I won't be taking additions of unofficial models or changes to official models which look like more than corrections of errors.  My hope is that these branches in particular represent somewhere that the official branches will end up.  Other branches could of course be made for other purposes.

If we want to additionally talk about a way to help organize unofficial models, I'm game.  I would have to review what the official way is though since I don't actually know yet...  As is, vendors can make their own branches from whatever they want (official, master_plus_pull_requests, etc) and add their unofficial models or even those of other vendors if they want them grouped together.

@bobfox, could we at least get Travis going so PRs can be verified against the existing tools provided by the repo?

**Comment by cfstras** [comment]
@altendky As a sidenote, could you change the default branch for your repo to `master_plus_pull_requests`, so the additional value of your repo is more readily apparent to newcomers?

**Comment by altendky** [comment]
@cfstras, thanks for the suggestion.  I have updated both default branches and added notes to the readmes.

**Comment by garretfick** [comment]
I would be very intersted in getting travis setup. I have done it previously for a private fork of this and could contribute that.

**Comment by altendky** [comment]
@garretfick if you have time to review #37 and point out any issues, that would be great.  My PR-coalescing-fork should be building with that PR (https://travis-ci.org/altendky/models).

**Comment by garretfick** [comment]
The change looks reasonable to me. Only comment is that using shell scripts means the build only works on Linux (depends on installing a cpakcage).

I did something similar, but with Python so that it could run elsewhere.
https://github.com/garretfick/models

**Comment by altendky** [comment]
@garretfick I agree that `make` isn't really being put to any use here.  Though Python itself is a dependency as well.  Python is my daily work language but I don't know if that's common or not for people working with this models repo. Anyways, ticket/PR away I guess for when they do get reviewed.

**Comment by garretfick** [comment]
Absolutely - they are both dependencies. My rationale for python was it is an easier dependency to consume across multiple platforms. But as you said, hopefully it will get reviewed sometime.

**Comment by garretfick** [comment]
@bobfox Any word on when this repo might move forward again?

**Comment by bobfox** [comment]
It will move forward shorty. We are finalizing drafts for updated modeling
and some addition DER models. We will also be addressing the open issues
and pull requests.

Bob

**Comment by silvia2019** [comment]
Now working through these issues.

**Comment by altendky** [comment]
Welcome @silvia2019.  I tried to keep my PRs tidy here and in https://github.com/sunspec/pysunspec but let me know if I can help clarify anything with them.

Cheers,
-kyle

**Comment by silvia2019** [comment]
Thank you.

**Comment by cfstras** [comment]
I guess we can close this now!
@silvia2019 thank you for your work so far!
