### ISSUE TITLE
Model #64112: "Ninty" is a misspelling of "Ninety"

### ISSUE THREAD

**Issue by andig** [sunspec/models#55]
Found a couple ones:

````
❯ ./bin/misspell spec/smdx/smdx*.xml
spec/smdx/smdx_00010.xml:58:21: "Unkown" is a misspelling of "Unknown"
spec/smdx/smdx_00007.xml:106:40: "reponse" is a misspelling of "response"
spec/smdx/smdx_00004.xml:84:53: "specifed" is a misspelling of "specified"
spec/smdx/smdx_00004.xml:185:40: "reponse" is a misspelling of "response"
spec/smdx/smdx_00003.xml:74:53: "specifed" is a misspelling of "specified"
spec/smdx/smdx_00014.xml:32:55: "capabilites" is a misspelling of "capabilities"
spec/smdx/smdx_00305.xml:36:19: "Lattitude" is a misspelling of "Latitude"
spec/smdx/smdx_00501.xml:79:47: "producting" is a misspelling of "production"
spec/smdx/smdx_00502.xml:83:47: "producting" is a misspelling of "production"
spec/smdx/smdx_64020.xml:191:72: "writting" is a misspelling of "writing"
spec/smdx/smdx_64020.xml:196:72: "writting" is a misspelling of "writing"
spec/smdx/smdx_64112.xml:35:20: "Ninty" is a misspelling of "Ninety"
spec/smdx/smdx_64112.xml:36:20: "Ninty" is a misspelling of "Ninety"
spec/smdx/smdx_64112.xml:224:18: "Ninty" is a misspelling of "Ninety"
spec/smdx/smdx_64112.xml:229:18: "Ninty" is a misspelling of "Ninety"
````

**Comment by nielsbasjes** [comment]
There seems to be a big overlap with this (which has already been merged)
https://github.com/sunspec/models/pull/43

**Comment by andig** [comment]
> There seems to be a big overlap with this (which has already been merged)

Actually, there shouldn't be as I've pulled the models before. E.g., my check didn't hit on the "digital" typos. Afaiks these should be unique.

**Comment by silvia2019** [comment]
Thank you for the list of typos.  Went through them and verified that most have been addressed in  a previous commit:

- spec/smdx/smdx_00010.xml:58:21: "Unkown" is a misspelling of "Unknown"

    Fixed in pull request:  https://github.com/sunspec/models/pull/43

- spec/smdx/smdx_00007.xml:106:40: "reponse" is a misspelling of "response"

    Fixed in pull request:  https://github.com/sunspec/models/pull/43

- spec/smdx/smdx_00004.xml:84:53: "specifed" is a misspelling of "specified"

    Fixed in pull request:  https://github.com/sunspec/models/pull/43

- spec/smdx/smdx_00004.xml:185:40: "reponse" is a misspelling of "response"

    Fixed in pull request:  https://github.com/sunspec/models/pull/43

- spec/smdx/smdx_00003.xml:74:53: "specifed" is a misspelling of "specified"

     Fixed in pull request:  https://github.com/sunspec/models/pull/43

- spec/smdx/smdx_00014.xml:32:55: "capabilites" is a misspelling of "capabilities"

    Fixed in pull request:  https://github.com/sunspec/models/pull/43

- spec/smdx/smdx_00305.xml:36:19: "Lattitude" is a misspelling of "Latitude"

    Fixed in pull request:  https://github.com/sunspec/models/pull/43

- spec/smdx/smdx_00501.xml:79:47: "producting" is a misspelling of "production"

    Fixed in pull request:  https://github.com/sunspec/models/pull/43

- spec/smdx/smdx_00502.xml:83:47: "producting" is a misspelling of "production"

    Fixed in pull request:  https://github.com/sunspec/models/pull/43

- spec/smdx/smdx_64020.xml:191:72: "writting" is a misspelling of "writing"

    Fixed in pull request:  https://github.com/sunspec/models/pull/43

- spec/smdx/smdx_64020.xml:196:72: "writting" is a misspelling of "writing"

    Fixed in pull request:  https://github.com/sunspec/models/pull/43

The id's for model 64112 listed below are misspelled. However, because these are Symbol IDs we need to investigate if it's feasible to fix them now.

- spec/smdx/smdx_64112.xml:35:20: "Ninty" is a misspelling of "Ninety"
- spec/smdx/smdx_64112.xml:36:20: "Ninty" is a misspelling of "Ninety"
- spec/smdx/smdx_64112.xml:224:18: "Ninty" is a misspelling of "Ninety"
- spec/smdx/smdx_64112.xml:229:18: "Ninty" is a misspelling of "Ninety"

**Comment by andig** [comment]
My bad. Didn't realized I was stuck in a detached head state and my pull wasn't effective. Please excuse me.

**Comment by nielsbasjes** [comment]
The way I look at these XMLs is that they are the definition of the mapping from the binary (registers and bit layouts) out of the devices and the functional meaning.
The IDs (i.e. like the "Ninty" situation) seem only to be used as the link between the block/point and the strings that describe them.

Changing these IDs (i.e. fixing the spelling errors) does not change this "binary to meaning" mapping.
So I propose we fix the "Ninty" and the "DiSCHARGE" examples as mentioned before here https://github.com/sunspec/models/pull/43#issuecomment-515760102 and again in this issue.

**Comment by nielsbasjes** [comment]
I was just thinking: The same holds for changing the type of the MAC from uint64 to eui48.
The bits and their meaning do not change. 
So changing this in these XMLs can be done without any problems.

**Comment by altendky** [comment]
@nielsbasjes within the context of this repo I think that may be true.  But wouldn't the point ID be the sort of thing that anything using these XML files would be expected to identify the point by?  Regardless, there must be a path by which things can be corrected.  v2.0 + mapping from old IDs to new if nothing else.

**Comment by silvia2019** [comment]
Thank you for all of the input.  Turns out that mode 64112 is a vendor specific model and it is being hosted here.  We cannot change it. 

 A list of vendor extension ranges can be found under: https://sunspec.org/download/vendor-extensions/

I'm closing the issue for now.
